version: '3'
services:
  db:
    container_name: tech.stinnovasv.com
    image: 14.0
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5501:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - net-odoo
volumes:
  db-data:
networks:
  net-odoo:
    name: net-odoo

