version: '3'
services:
  odoo:
    container_name: ${ODOO_HOST}
    image: ${ODOO_IMAGE}
    ports:
      - "${ODOO_PORT}:8069"
      - "${LONGPOLLING_PORT}:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
networks:
  default:
    external:
      name: net-odoo
volumes:
  odoo-data:

